"""
Archiver module for Thread-Auto.

This module handles archiving processed news into Markdown files
daily, similar to the GENEXIS-AI/DailyNews repository structure.
"""

import os
from datetime import datetime
from typing import Dict, Any, Optional

def get_archive_path(date: Optional[datetime] = None) -> str:
    """
    Get the absolute path for the daily archive markdown file.

    Args:
        date: The date to generate the filename for (default: today).

    Returns:
        Absolute file path (e.g., /path/to/archive/2024-01-20.md).
    """
    if date is None:
        date = datetime.now()
    
    filename = date.strftime("%Y-%m-%d.md")
    archive_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "archive")
    
    # Create archive directory if it doesn't exist
    if not os.path.exists(archive_dir):
        os.makedirs(archive_dir)
        
    return os.path.join(archive_dir, filename)

def save_to_archive(
    data: Dict[str, Any],
    image_url: Optional[str],
    source_url: str,
    title: str,
    provider: str,
    model: str
) -> str:
    """
    Save the analyzed news content to a daily Markdown archive file.

    Args:
        data: AI-analyzed content dictionary.
        image_url: URL of the news image (or None).
        source_url: Original URL of the news article.
        title: Title of the news article.
        provider: AI provider used (e.g., 'Groq', 'Gemini').
        model: AI model used.

    Returns:
        Path to the saved markdown file.
    """
    filepath = get_archive_path()
    
    # Prepare markdown content
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    content_lines = []
    
    # Header if file is new
    if not os.path.exists(filepath):
        content_lines.append(f"# Daily Tech News Archive\n")
        content_lines.append(f"Auto-generated by Thread-Auto\n")
    
    # News Entry
    content_lines.append(f"\n## [{datetime.now().strftime('%H:%M')}] {title}\n")
    
    if image_url:
        content_lines.append(f"![News Image]({image_url})\n")
    
    content_lines.append(f"**AI Analysis** ({provider} / {model})\n")
    
    # Main Post
    main_post = data.get("main_post", "")
    content_lines.append(f"> {main_post.replace(chr(10), chr(10) + '> ')}\n")
    
    # Thread Replies
    if data.get("type") == "multi":
        content_lines.append("### 상세 분석\n")
        for reply in data.get("replies", []):
            content_lines.append(f"- {reply}\n")
            
    # Footer
    content_lines.append(f"\n[원본 기사 보기]({source_url})\n")
    content_lines.append(f"---\n")

    # Append to file
    with open(filepath, "a", encoding="utf-8") as f:
        f.writelines(content_lines)
        
    print(f"✅ 아카이브 저장 완료: {filepath}")
    return filepath
