"""
Write a daily operational log for GitHub Actions runs.

The log is intentionally small, but it gives every scheduled run a real
project artifact even when there are no new articles to archive.
"""

import os
import sys
import json
from datetime import datetime, timedelta, timezone
from pathlib import Path

for stream in (sys.stdout, sys.stderr):
    if hasattr(stream, "reconfigure"):
        stream.reconfigure(encoding="utf-8")

ROOT_DIR = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT_DIR))

from archiver import list_archive_files
from source_registry import (
    calculate_collection_score,
    get_disabled_sources,
    get_enabled_sources,
)


LOG_DIR = ROOT_DIR / "logs" / "daily"
LAST_RUN_SUMMARY_PATH = ROOT_DIR / ".thread_auto_last_run.json"
KST = timezone(timedelta(hours=9), name="KST")


def relative_path(path: str) -> str:
    """Return a repo-relative path for readable logs."""
    try:
        return str(Path(path).resolve().relative_to(ROOT_DIR)).replace("\\", "/")
    except ValueError:
        return str(path)


def latest_archive_path() -> str:
    """Return the latest archive path, or a clear placeholder."""
    archive_files = list_archive_files()
    if not archive_files:
        return "none"

    return relative_path(archive_files[0])


def read_last_run_summary() -> dict:
    """Read the latest pipeline summary written by main.py."""
    if not LAST_RUN_SUMMARY_PATH.exists():
        return {}

    try:
        return json.loads(LAST_RUN_SUMMARY_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def format_pipeline_stats(stats: dict) -> str:
    """Format compact pipeline counters for markdown logs."""
    if not stats:
        return "none"

    return ", ".join(f"{key}={value}" for key, value in sorted(stats.items()))


def format_provider_selection(selection: list) -> str:
    """Format provider selection diagnostics for markdown logs."""
    if not selection:
        return "none"

    return ", ".join(str(item) for item in selection)


def write_daily_run_log(now: datetime | None = None) -> Path:
    """Create or update today's daily run log."""
    now = now or datetime.now(KST)
    year = now.strftime("%Y")
    month = now.strftime("%m월")
    date_slug = now.strftime("%Y-%m-%d")

    log_dir = LOG_DIR / year / month
    log_dir.mkdir(parents=True, exist_ok=True)
    log_path = log_dir / f"{date_slug}.md"

    enabled_sources = get_enabled_sources()
    disabled_sources = get_disabled_sources()
    dry_run = os.environ.get("DRY_RUN", "true")
    summary = read_last_run_summary()
    provider = summary.get("ai_provider", os.environ.get("AI_PROVIDER", "openrouter"))
    preferred_provider = summary.get("preferred_ai_provider", provider)

    disabled_text = (
        ", ".join(sorted(disabled_sources.keys())) if disabled_sources else "none"
    )

    log_path.write_text(
        "\n".join(
            [
                f"# Thread-Auto Daily Run Log ({date_slug})",
                "",
                f"- Run time (KST): {now.strftime('%Y-%m-%d %H:%M:%S')}",
                f"- AI provider: {provider}",
                f"- Preferred AI provider: {preferred_provider}",
                f"- Provider selection: {format_provider_selection(summary.get('provider_selection', []))}",
                f"- Dry run: {dry_run}",
                f"- Pipeline status: {summary.get('status', 'unknown')}",
                f"- Archived articles: {summary.get('total_articles', 'unknown')}",
                f"- Pipeline error: {summary.get('error', 'none') or 'none'}",
                f"- Fallback archive: {summary.get('fallback_archive_enabled', 'unknown')}",
                f"- Pipeline stats: {format_pipeline_stats(summary.get('stats', {}))}",
                f"- Enabled sources: {len(enabled_sources)}",
                f"- Collection score: {calculate_collection_score()}/100",
                f"- Disabled sources: {disabled_text}",
                f"- Latest archive: {latest_archive_path()}",
                "",
                "This file is generated by GitHub Actions as a daily operational record.",
                "",
            ]
        ),
        encoding="utf-8",
    )

    return log_path


def main() -> None:
    log_path = write_daily_run_log()
    print(f"Daily run log written: {relative_path(str(log_path))}")


if __name__ == "__main__":
    main()
